import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeProviderWrapper from '@/theme/theme-provider-wrapper';
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Neure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        background: 'linear-gradient(to right, #434343 0%, black 100%)',
        overflowX: 'hidden',
        overflowY: 'auto',
      }}>
        <ThemeProviderWrapper options={{ key: 'mui-theme' }}>
          <AppRouterCacheProvider>
            <ClerkProvider
              appearance={{
                baseTheme: dark,
                variables: {
                  colorPrimary: '#90caf9',
                },
                elements: {
                  userButtonPopoverCard: {
                    boxShadow: '0px 0px 10px 0px #000000',
                  },
                }
              }}
            >
              {children}
            </ClerkProvider>
          </AppRouterCacheProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
